# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b43aea8cc79d1e94e94056fae29350b07b14aee4b82e7900c37681001243c9773bbbe463c067962b4db967d40da59f8080c82bdec1c001296bd490b1d4440b76

test:
  secret_key_base: 2e079ee61ee74a4bddb730c9a9e76fa1b2f66f8543335bb72a3bf7df05936a35a6dc4a54e544d700a103d8bd8eb223e6a3593528d9cc804e7ee4932a882d2f9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
